export { default as Sorvete } from './Sorvete'
export { default as SorveteComum } from './SorveteComum'
export { default as SorveteDiet } from './SorveteDiet'
export { default as SorveteComCalda } from './SorveteComCalda'
export { default as SorveteNoCopo } from './SorveteNoCopo'
export { default as SorveteNaCasq } from './SorveteNaCasq'
export { default as SorveteNaTaca } from './SorveteNaTaca'
export { default as Decorator } from './Decorator'
export { Sabores } from './Sabores'
export { Caldas } from './Caldas'
export { Tipos } from './Tipos'
